### ISSUE TITLE
Algo no ha ido bien

### ISSUE THREAD

**Issue by mirenbz** [NikolasQuintano/NikolasQuintano.github.io#5]
Hola @NikolasQuintano , a pesar de que has podido terminar el tutorial, algo no ha ido bien: si te fijas, tu post no está accesible desde tu página de GitHub Pages en https://nikolasquintano.github.io/github-pages/  Por algún motivo, parece que el tema no se está aplicando. 

Estoy pensando que podría deberse a que has añadido `theme: minima` en la primera línea del archivo `_config.yml`:

https://github.com/NikolasQuintano/github-pages/blob/9a13ca963d7714f9e0ac15fbb34b20f4381adbaa/_config.yml#L1

¿Puedes mover esa línea al final de archivo, por favor? Y vemos si resuelve algo.

**Comment by NikolasQuintano** [comment]
Ya lo he arreglado @mberasategi

**Comment by mirenbz** [comment]
OK! Te dejo el paso 1 en #7
